#define MENU_CURSOR ">"  

#define MENU_TITLE1 "Marshmallow"
#define MENU_TITLE2 "  DOOM"

#define MENU_HELLSCAPE "    PKE Meter Widget"
#define MENU_SKILL "Change Skill"
#define MENU_INV "Inventory Menu"
#define MENU_BOTS "Bots"
#define MENU_MSGS "Messages"
#define MENU_SEPPUKU "Suicide"
#define MENU_SKIP "Change Map"
#define MENU_RESTART "Restart Level"
#define MENU_MUSIC "Doom DJ"

#define PKEHINT_RADIUS "RADIUS: "
#define PKEHINT_SMALL "LOW"
#define PKEHINT_MEDIUM "MED"
#define PKEHINT_LARGE "HIGH"

#define PKERADIUS_STRING1 "SEARCH RADIUS SET TO SMALL."
#define PKERADIUS_STRING2 "SEARCH RADIUS SET TO MEDIUM."
#define PKERADIUS_STRING3 "SEARCH RADIUS SET TO LARGE."

#define ORDERS  "ORDERS: "
#define COVER "FOLLOWING"
#define SEEK "CLEAN HOUSE"
#define TAKEPOINT "ASSIGNMENT"
#define PATROL "PATROLLING"
#define BACKTRACK "RETURN HOME"
#define NONE "NO ORDERS"
#define STATE "STATE: "
#define FOLLOW "READY"
#define USING "USING DOOR"
#define BOTSCATTER "SCATTER"
#define FOLLOWPATH "PATHFINDING"
#define REGROUP "REGROUPING"
#define STAY "WAITING"
#define ATTACK "ATTACKING"
#define AWAIT "AWAITING TARGET"
#define WAIT "RESPAWNED"
#define HEALTH "HEALTH: "
#define CHAT "CHAT: "  
#define ROAM "ROAMING"
#define SEARCHING "SEARCHING"

#define ORDERMSGPATROL "ORDER: SECURE THIS AREA"
#define ORDERMSGFOLLOW "ORDER: FOLLOW SQUAD LEADER"
#define ORDERMSGHOLD "ORDER: HOLD POSITION"
#define ORDERSMSGTAKE "ORDER: STAND BY FOR TARGET"
#define ORDERSMSGASSIGN "ORDER: ENGAGE TARGET"

#define REGROUPSQUAD "ORDER: SQUAD REGROUP"
#define BOTCHATFOLLOW "LEAD THE WAY!"   // used to be "YOU TAKE POINT!" 
#define BOTCHATWAIT "WAITING HERE!"
#define BOTCHATRESPAWN "RESPAWNED!"
#define BOTCHATENEMYSPOT "ENEMY SPOTTED!"
#define BOTCHATCOVER "WATCH OUT!"
#define BOTCHATGETHIM "LET'S GET HIM!"
#define BOTCHATFIRE "I'M UNDER FIRE!"
#define BOTCHATSTUCK "I WILL CATCH UP!"

#define TARGETHPBOSSES "    BOSSES"
#define TARGETHPALL "     ALL"
#define DYNAMICMUSIC_ON "    MARSHMALLOW"
#define DYNAMICMUSIC_OFF "    VANILLA"
#define OPTION_ON "     ON"
#define OPTION_OFF "     OFF"
#define BLANK_LINE ""			

#define SONG_ENABLED "    PLAY"
#define SONG_DISABLED "   SKIP"

#define CHANGEFFECT "CHANGES TAKE EFFECT NEXT MAP!"
#define CHANGESBOX "SANDBOX MODE DISABLED NEXT MAP!"

#define NOWADSTEALING "ENABLE WAD STEALING FOR DOOM 2 MONSTERS!" 
#define FIGHT "FIGHT!"
#define SANDBOXDONE "SANDBOX COMPLETED!"
#define ONLYHOST "ONLY THE HOST CAN START THE BATTLE!"
#define NOMONSTERS "NO MONSTERS PLACED YET!"
#define RESTORESANDBOX "RESTORING SAVED SANDBOX..."

#define PICKMAP "CHOOSE A MAP FIRST!"

#define FOUNDBULL "YOU FOUND SOME BULLETS!"
#define FOUNDROCK "YOU FOUND SOME ROCKETS!"
#define FOUNDCELL "YOU FOUND SOME CELLS!"
#define FOUNDBUCK "YOU FOUND SOME SHELLS!"

#define GIVEALL "GIVING ALL ITEMS!"

#define EKGOFF "EKG MODE DISABLED!"
#define EKGON "LUDICROUS GIBS!"

#define ABORTMAP "MAP ABORTED!"

#define NM2NEXT "NIGHTMARE 2.0 SKILL NEXT MAP!"

#define NM2AL "NIGHTMARE 2.0 ALREADY ENABLED!"

#define SKILL1 "ITYTD SKILL NEXT MAP!"
#define SKILL2 "HNTR SKILL NEXT MAP!"
#define SKILL3 "HMP SKILL NEXT MAP!"
#define SKILL4 "ULTRA VIOLENCE SKILL NEXT MAP!"
#define SKILL5 "NIGHTMARE SKILL NEXT MAP!"

#define NMRON "NIGHTMARE RESPAWNING ENABLED."
#define NMROFF "NIGHTMARE RESPAWNING DISABLED."

#define PHYSON "INSANE PHYSICS ENABLED!"
#define PHYSOFF "INSANE PHYSICS DISABLED!"

#define PHYSMODEOFF "  OFF"
#define PHYSMODEONE "  BOOSTED"
#define PHYSMODETWO "  INSANE"

#define LIGHTINGOFF "  OFF"
#define LIGHTINGCRT "  VINTAGE CRT"
#define LIGHTINGDOOM3 "  DOOM 3"

#define AU_ON "AUTO-USE ENABLED"
#define AU_OFF "AUTO-USE DISABLED"
#define REDOMAP "RESTARTING MAP!"

#define WWWCHEAT "WOUNDLESS WITH WEAPONS ON!"

#define EXHAUSTED "YOU FEEL EXHAUSTED!"

#define SKILL_ITYTD "CURRENTLY USING ITYTD SKILL LEVEL."
#define SKILL_HNTR "CURRENTLY USING HNTR SKILL LEVEL."
#define SKILL_HMP "CURRENTLY USING HMP SKILL LEVEL."
#define SKILL_UV "CURRENTLY USING UV SKILL LEVEL."
#define SKILL_NM "CURRENTLY USING NM SKILL LEVEL."

#define ALTNM "NIGHTMARE 2.0 SKILL LEVEL!"
#define ALTUV "UV 2.0 SKILL LEVEL!"

#define CONFIRMSUICIDE "PRESS TO CONFIRM SUICIDE..."

#define FFOFF "FRIENDLY FIRE DISABLED!"
#define FFON "FRIENDLY FIRE ENABLED!"

#define LOWAMMO "AMMO IS LOW!"

#define NODROP "NOT ENOUGH AMMO TO DROP A BACKPACK!"
#define YOUDROP "YOU DROPPED A BACKPACK OF AMMO."

#define DEADDROP "YOU CANNOT DROP ANYTHING WHILE DEAD!"

#define STOPFF "STOP ATTACKING TEAMMATES!"
#define MIRRORON "MIRROR DAMAGE ON!"

#define FOOTENG "MIGHTY FOOT ENGAGED!"

#define REDSCREENOFF "    OFF"
#define REDSCREENSHORT "    SHORT"
#define REDSCREENFULL "    FULL"

#define MENUBLACKLIST "  SONG BLACKLIST...   "

#define KILLEDNAZI "YOU KILLED A NAZI STORMTROOPER!"
#define KILLEDPOS "YOU KILLED A ZOMBIEMAN!"
#define KILLEDSARG "YOU KILLED A SARGEANT!"
#define KILLEDIMP "YOU KILLED AN IMP!"
#define KILLEDDEMON "YOU KILLED A DEMON!"
#define KILLEDSPEC "YOU KILLED A SPECTRE!"
#define KILLEDFATTY "YOU KILLED A MANCUBUS!"
#define KILLEDVILE "YOU KILLED AN ARCHVILE!"
#define KILLEDCYBER "YOU KILLED A CYBERDEMON!"
#define KILLEDBOSS "YOU KILLED A SPIDER MASTERMIND!"
#define KILLEDSKEL "YOU KILLED A REVENANT!"
#define KILLEDBARON "YOU KILLED A BARON OF HELL!"
#define KILLEDKNIGHT "YOU KILLED A HELL KNIGHT!"
#define KILLEDBABY "YOU KILLED AN ARACHNOTRON!"
#define KILLEDCGUY "YOU KILLED A CHAINGUNNER!"

#define PROMPTRADSUIT "PRESS 'R' TO USE RAD-SUIT!"
#define PROMPTMEDKIT "PRESS 'R' TO USE MEDKIT!"

#define YOUBERSERK "YOU ARE BERSERK! 10x PUNCH DAMAGE!"

#define ALREADYFULL "YOU ARE ALREADY AT FULL HEALTH!"

#define ADDEDINVUL "INVULNERABILITY ADDED TO INVENTORY!"
#define ADDEDINVIS "INVISIBILITY ADDED TO INVENTORY!"
#define ADDEDRADSUIT "RAD-SUIT ADDED TO INVENTORY!"
#define ADDEDMEDKIT "BERSERK! MEDKIT ADDED TO INVENTORY!"
#define ADDEDVISOR "GOGGLES ADDED TO INVENTORY!"
#define ADDEDAUTOMAP "AUTOMAP ADDED TO INVENTORY!"

#define USINGINVUL "USING INVULNERABILITY!"
#define USINGINVIS "USING INVISIBILITY!"
#define USINGRADSUIT "USING RAD-SUIT!"
#define USINGMEDKIT "USING MEDKIT!"
#define USINGVISOR "USING VISOR!"
#define USINGAUTOMAP "USING AUTOMAP!"

#define USEDMEDICAL "YOU USE SOME MEDICAL SUPPLIES!"

#define HAVEINVUL "YOU ALREADY HAVE THE INVULNERABILITY!"
#define HAVEMEDKIT "YOU ALREADY HAVE A MEDKIT!"
#define HAVEINVIS "YOU ALREADY HAVE THE INVISIBILITY!"
#define HAVERADSUIT "YOU ALREADY HAVE THE RAD-SUIT!"
#define HAVEVISOR "YOU ALREADY HAVE THE GOGGLES!"
#define HAVEAUTOMAP "YOU ALREADY HAVE THE AUTOMAP!"

#define SPIDERSPOT "A SPIDERDEMON HAS SPOTTED YOU!"
#define CYBERSPOT "A CYBERDEMON HAS SPOTTED YOU!"
#define VILESPOT "AN ARCHVILE HAS SPOTTED YOU!"

#define PLAYERSHOT "ANOTHER PLAYER SHOT YOU!"
#define SHOTPLAYER "YOU SHOT ANOTHER PLAYER!"

#define VILEDEAD "AN ARCHVILE HAS BEEN KILLED!"
#define CYBERDEAD "A CYBERDEMON HAS BEEN KILLED!"
#define SPIDERDEAD "A SPIDERDEMON HAS BEEN KILLED!"

#define WORLDDAMAGE "THE ENVIRONMENT DID DAMAGE TO YOU!"
#define MONSTERTRAP "A MONSTER WALKED INTO A TRAP!"
#define MONSTERFIGHT "MONSTERS ARE INFIGHTING."

#define INVRADSUIT "    RAD-SUIT"
#define INVINVUL "    INVULNERABILITY"
#define INVINVIS "    INVISIBILITY"
#define INVMEDKIT "    MEDKIT"
#define INVGOGGLES "    INFRARED GOGGLES"
#define INVAUTOMAP "    AUTO-MAP"

#define YOUSEPPUKU "YOU COMMIT SEPPUKU!"

#define INVRECOVERED "YOU RECOVERED YOUR INVENTORY!"

#define NAZIKILL "YOU WERE KILLED BY A STORMTROOPER!"
#define ZOMKILL "YOU WERE KILLED BY A ZOMBIEMAN!"
#define SGKILL "YOU WERE KILLED BY A SARGEANT!"
#define CGKILL "YOU WERE KILLED BY A CHAINGUNNER!"
#define IMPKILL "YOU WERE KILLED BY AN IMP!"
#define DEMONKILL "YOU WERE KILLED BY A DEMON!"
#define SPKILL "YOU WERE KILLED BY A SPECTRE!"
#define FATKILL "YOU WERE KILLED BY A MANCUBUS!"
#define VILEKILL "YOU WERE KILLED BY AN ARCHVILE!"
#define CYBERKILL "YOU WERE KILLED BY A CYBERDEMON!"
#define BOSSKILL "YOU WERE KILLED BY A SPIDERDEMON!"
#define SKELKILL "YOU WERE KILLED BY A REVENANT!"
#define BARONKILL "YOU WERE KILLED BY A BARON OF HELL!"
#define KNIGHTKILL "YOU WERE KILLED BY A HELL KNIGHT!"
#define BABYKILL "YOU WERE KILLED BY AN ARACHNOTRON!"

#define HURTSELF "YOU HURT YOURSELF!"
#define SELFDMGOFF "SELF-DAMAGE OFF!"

#define MISSILELOCK1 "MISSILE"
#define MISSILELOCK2 " LOCK-ON"

#define DANGERSYMBOL1 "*"
#define DANGERSYMBOL2 "**"
#define DANGERSYMBOL3 "***"
#define DANGERSYMBOL4 "****"
#define DANGERSYMBOL5 "*****"

#define PLAYLISTMODE1 "DYNAMIC"
#define PLAYLISTMODE2 "AMBIENT"
#define PLAYLISTMODE3 "SUSPENSEFUL"
#define PLAYLISTMODE4 "INTENSE"
#define PLAYLISTMODE5 "ALL SONGS"

#define THINGLABEL "Thing: "
#define SCORELABEL "TREASURE SCORE: "
#define REMAINLABEL "REMAINING: "
#define NOTREASURE "NO TREASURE FOUND!"
#define ALLTREASURE "ALL TREASURE COLLECTED!"
#define TREASURECONGRATS "ALL TREASURE COLLECTED!"

#define ALLMONSTERS "ALL MONSTERS ELIMINATED!"

#define PLASMALOW "WARNING: ENERGY CELLS LOW!"

#define PLASMALOW1 "WARNING:" 
#define PLASMALOW2 "ENERGY"
#define PLASMALOW3 "CELLS LOW!"

#define TARGETHP "TARGET HP: "

#define GOBUTTON "      GO!"
#define RESETBUTTON "     RESET"
#define WHICHMAP "    Choose Map:  "

#define HELPTITLE "* KEYBOARD REFERENCE *"
#define HELPLINE1 "'M' - Datapad"
#define HELPLINE2 "'V' - Inventory"
#define HELPLINE3 "'P' - PKE Meter"
#define HELPLINE4 "'F' - Squad: Regroup"
#define HELPLINE5 "'T' - Squad: Assign Target"
#define HELPLINE6 "Hold USE for Squad Command Menu"
#define HELPLINE_RANGE "'R' - Radar Range"

#define SPAWNINGOBJECT "SPAWNING OBJECT."
#define WAITDIPSHIT "WAIT A MOMENT TO PLACE ANOTHER..."

#define TIP "   TIP: "

#define HELPLINE8 "Hold SHIFT to pull bots closer"

#define HELPLINE7 "'G' - Drop Ammo"

#define HELPLINE9 "'H' - Toggle Help"

#define HELPLINE_PGUPDN "PGUP, PGDN - select"
#define HELPLINE_INSERT "       INSERT - spawn"
#define HELPLINE_BRACKETS "'[' or ']' - select"
#define HELPLINE_SLASH "         '\\' - spawn"
#define HELPLINE_M "         'M' - go back"

#define SANDBOXTIP "         'B' - battle"

#define RANDOMLEVEL "    Skip to Random Level"

#define INVENTORYTITLE "   INVENTORY"
#define INVEMPTY "    * NO ITEMS FOUND *"

#define TREASURE "TREASURE!"
#define TREASURE_REDSKULL "TREASURE! BLOOD SKULL FOR +100 POINTS!"
#define TREASURE_BLUESKULL "TREASURE! ICE SKULL FOR +10 POINTS!"
#define TREASURE_YELLOWSKULL "TREASURE! GOLD SKULL FOR +50 POINTS!"

#define CHAINGUNLABEL "    CHAINGUN"
#define SHOTGUNLABEL "    SHOTGUN"

#define TREASURENORMAL "    SCARCE"
#define TREASUREFULL  "    ABUNDANT"

#define MODECOOP "COOPERATIVE"
#define MODEDM "DEATHMATCH"
#define MODESP "SOLO PLAY"
#define MODESBOX "SANDBOX"

#define SHORTER "    SHORTER"
#define LONGER "    LONGER"

#define BOT1LABEL "BOT1: "
#define BOT2LABEL "BOT2: "
#define BOT3LABEL "BOT3: "

#define MONSTERDIED "A MONSTER DIED OF NATURAL CAUSES!"
#define ENVKILL "A PLAYER DIED OF NATURAL CAUSES!"
#define KILLENV  "KILLED BY AN ENVIRONMENTAL DANGER!"
#define SOMEONEBLEW "A PLAYER BLEW THEMSELF UP!"
#define YOUBLEW "YOU BLEW YOURSELF UP!"
#define KILLBYPLAYER "YOU WERE KILLED BY ANOTHER PLAYER!"
#define KILLPLAYER "YOU KILLED ANOTHER PLAYER!"

#define DEMONSPHEREHEALS "A DEMONSPHERE HEALS YOU!"
#define FOUNDBACKPACK "YOU FOUND SOME AMMO!"
#define SOULSPHEREHEALS "A SOULSPHERE HEALS YOU!"
#define MEGAHEALS "A MEGASPHERE HEALS YOU!"

#define AMBIENTSONGS "DOOM DJ: AMBIENT"
#define SUSPENSEFULSONGS "DOOM DJ: SUSPENSEFUL"
#define INTENSESONGS "DOOM DJ: INTENSE"
#define BOSSSONGS "DOOM DJ: BOSS"
#define VICTORYSONGS "DOOM DJ: VICTORY"
#define ALLSONGS "DOOM DJ: EVERYTHING PLAYLIST"
#define NEXTSONG "DOOM DJ: NEXT TRACK"

#define STATSOK "PLAYER STATS SAVED."
#define STATSHINT "FINISH LEVEL TO SAVE A PROFILE."

#define VANILLA "    DOOM"
#define LUDICROUS "    LUDICROUS"
#define GROOVY "    GROOVY"
#define BRUTAL "    BRUTAL"

#define BOTCOMMANDTITLE " * Squad Commands *"
#define FOLLOWME "    'F' - Follow Me"
#define SCATTER "    'P' - Patrol"
#define HOLDPOSITION "    'H' - Hold Position"